### ISSUE TITLE
A typo in Module 11?

### ISSUE THREAD

**Issue by RealFakeAccount** [siefkenj/IBLLinearAlgebra#201]
This is from module 11,  page 131:

![image](https://user-images.githubusercontent.com/63186767/98147733-b8d9a400-1e9a-11eb-8320-a06952052d12.png)

Just wanna make sure this is a typo, since the definition "translated subspace" only occurred once (there) through the whole book.

If it is the case, please let me know and I'll fix it by opening a pull request.

**Comment by luema** [comment]
Maybe translated span?
Spans are subspaces and subspaces are spans, they just describe the same object in slightly different ways. 
So translated subspaces are translated spans, which shows up a lot in the book.

I think translated subspace is used here because the context was about fundamental subspaces?

**Comment by RealFakeAccount** [comment]
> I think translated subspaces was used here because the context was about fundamental subspaces?

the context here is discussing the relationship between Mx=b and null space.

> Maybe translated span?

Yes that's what I want to say. see the line right below this _"... and may therefore be written as a translated span"_, It is using "translated span" But if "translated subspace" is also fine here, please close this issue.

**Comment by luema** [comment]
I think you can just open a PR with the change and it'll get merged if it's correct. That way the prof only has to check github once. 

BTW, good catch.
