### ISSUE TITLE
Correction in first Example page 1

### ISSUE THREAD

**Issue by RamenRevelation** [siefkenj/IBLLinearAlgebra#79]
Rather than n being a whole number, shouldn't it be a natural number. If it is left as a whole number it could be set to 0. and the final value for 2n would be 0. There is no way to get 0 from m+1 if m is an odd whole number. 

Apologies if this isn't the best way to bring this to your attention, I haven't used github or git before and I couldn't find any other to contact you.

**Comment by RamenRevelation** [comment]
This of course depends on the definition of natural numbers, it seems in the text to also consider 0 as a natural number. I don't think this definition is that useful because there would be no difference between natural and whole numbers.

**Comment by siefkenj** [comment]
Can you tell me what line/page you are referring to?

**Comment by RamenRevelation** [comment]
problemsets-mat223/modules/module1.tex on line 52 it talks about set A being expressible as 2n for n being some whole number. Instead of using "natural" and "whole" to describe 'n', it might be simpler to describe 'n' as a positive integer. This eliminates the confusion whether 0 is a natural or whole number since students may be taught either definition and the set of whole numbers isn't described in lines 104-111. 
Also it might be useful to add a description of how to denote the set of positive integers (Z<sup>≥0</sup> or Z<sup>+</sup>) in set notation on line 104-111. 

Once again not sure how github really works so I'm not sure those are the only files you need to make changes to in order to change the whole textbook. Thanks

**Comment by siefkenj** [comment]
Thanks. If you ever want to reference a line number in github, you can click a line number in the code and a little "..." will show. You can then select  "Copy permalink" and get a URL that will directly reference that line of code.

As for the proof, negative numbers can be even too. The `integers` is the formal word for `whole number`. More sophisticated notation and terminology could be used in this example, but plain language was used on purpose because it comes early in the text before formal terms are introduced.
